#!/usr/bin/env php
<?php
/*
 * This file is part of Autoload Generator.
 *
 * (c) Herve Seignole <herve.seignole@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require_once __DIR__ . '/src/SimpleAutoloader/CacheGenerator.php';

$cacheGenerator = new \SimpleAutoloader\CacheGenerator();

if (count($errors = $cacheGenerator->run($argv)) != 0) {
    echo $cacheGenerator->help($errors);
    exit(1);
}
